### ISSUE TITLE
Fix typo still in CT_Stroke.xml

### ISSUE THREAD

**Issue by sebarton69** [ACRCode/acr_assist_modules#19]
In the CT_Stroke.xml file (https://github.com/ACRCode/acr_assist_modules/blob/master/CDE/NeuroCDE's/CT%20Stroke/CT_Stroke.xml), the Hint for the <IntegerDataElement Id="midlineshift"...> element should have "midlineshift" changed to "Midline shift".

**Comment by smitakabra** [comment]
This has been fixed

**Comment by sebarton69** [comment]
This is still an issue in the current CT_Stroke.xml file:  <Hint>midlineshift in mm</Hint>

**Comment by smitakabra** [comment]
Hi Steve, 

CAn you please look into the git CT stroke xml shows midline shift as label  - https://github.com/ACRCode/acr_assist_modules/blob/master/CDE/NeuroCDE's/CT%20Stroke/CT_Stroke.xml

Please let me know if I am missing anything

**Comment by sebarton69** [comment]
You are correct that the Label has been fixed, but the Hint field directly below it has not.

**Comment by smitakabra** [comment]
Sorry, got Hint text updated

**Comment by sebarton69** [comment]
Thank you.
